// import logo from "@/assets/home/kkk-logo.png";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";



export const metadata: Metadata = {
  title: "Eyanedwards-Upsocially Website",
  description: "Generated by create next app",
  icons: {
    // icon: logo.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  
      <body
        className={` antialiased`}
      >
        {/* <NavBar /> */}
        {/* <ReduxProvider>{children}</ReduxProvider> */}
        {children}
        <Toaster />

        {/* <Footer /> */}
      </body>
    </html>
  );
}
